changelog:
  exclude:
    labels:
      - docs
      - research
  categories:
    - title: Breaking Changes 🛠
      labels:
        - major
    - title: Exciting New Features 🎉
      labels:
        - feature
    - title: Bug Fixings
      labels:
        - bug
