name: Deploy

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install
        continue-on-error: false
        run: npm ci

      - name: Test
        continue-on-error: false
        run: npm run test

      - name: Build
        continue-on-error: false
        run: npm run build

      - name: Author
        continue-on-error: false
        run: |
          cd example
          git config --local user.email "ann.bystrova96@mail.ru"
          git config --local user.name "Ann Bystrova"

      - name: Predeploy
        continue-on-error: false
        run: npm run predeploy

      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: ann.bystrova96@mail.ru
          build_dir: example/build
