name: 'Develop'
on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  changelog:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        continue-on-error: false
        id: package_version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Generate changelog
        continue-on-error: false
        id: github_changelog
        uses: mikepenz/release-changelog-builder-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: "configs/configuration_changelog.json"

      - name: Write changelog
        continue-on-error: false
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ steps.package_version.outputs.current-version }}
          release-notes: ${{ steps.github_changelog.outputs.changelog }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: develop
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

#      - name: Commit changelog
#        run: |
#          git config --local user.email "ann.bystrova96@mail.ru"
#          git config --local user.name "Ann Bystrova"
#          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"
#
#      - name: Push changes
#        env:
#          CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          git push "https://Ann2827:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:develop
