name: 'Feature'
on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install
        continue-on-error: false
        run: npm ci

      - name: Build
        continue-on-error: false
        run: npm run build

      - name: Test
        continue-on-error: false
        run: npm run test

      - name: Author
        continue-on-error: false
        run: |
          cd example
          git config --local user.email "ann.bystrova96@mail.ru"
          git config --local user.name "Ann Bystrova"

      - name: Predeploy
        continue-on-error: false
        run: npm run predeploy

  version:
    if: github.event_name == 'push' && (
      startsWith(github.event.head_commit.message, 'feat:') ||
      startsWith(github.event.head_commit.message, 'fix:') ||
      startsWith(github.event.head_commit.message, 'major:'))
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Automated Version Bump
        id: bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: 'major:'
          minor-wording: 'feat:'
          patch-wording: 'fix:'
          tag-prefix: 'v'
          skip-tag: 'true'
