name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get version
      id: package_version
      uses: martinbeentjes/npm-get-version-action@master

    - name: Generate release
      id: github_release
      uses: mikepenz/release-changelog-builder-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        configuration: "configs/configuration_release.json"

    - name: Create Release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ steps.package_version.outputs.current-version }}
        name: ${{ steps.package_version.outputs.current-version }}
        body: ${{steps.github_release.outputs.changelog}}
        owner: Ann2827
        repo: library-react-hooks
        token: ${{ secrets.GITHUB_TOKEN }}
