name: 'CI'
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send greeting
        run: echo "Hello!!"

  version:
    if: github.event_name == 'pull_request' &&  github.ref_name == 'develop' && (
      startsWith(github.event.head_commit.message, 'feat:') ||
      startsWith(github.event.head_commit.message, 'fix:') ||
      startsWith(github.event.head_commit.message, 'major:'))
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Automated Version Bump
        id: bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: 'major:'
          minor-wording: 'feat:'
          patch-wording: 'fix:'
          target-branch: 'develop'
          tag-prefix: 'v'

  changelog:
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changelog
        run: |
          git config --local user.email "ann.bystrova96@mail.ru"
          git config --local user.name "Ann Bystrova"
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"

      - name: Push changes
        env:
          CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push "https://Ann2827:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:develop

#  build:
#    #    if: github.event_name  == 'pull_request'
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '16'
#      - name: Install
#        run: npm ci
#      - name: Build
#        run: npm run build
#      - name: Test
#        run: npm run test
#      - name: Author
#        run: |
#          cd example
#          git config --global user.email "ann.bystrova96@mail.ru"
#          git config --global user.name "Ann Bystrova"
#      - name: Deploy
#        run: |
#          npm run predeploy
#          npm run deploy

#  release:
#    runs-on: ubuntu-latest
##    needs: [build]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Automated Version Bump
#        id: bump
#        uses: 'phips28/gh-action-bump-version@master'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          major-wording: 'major++'
#          minor-wording: 'minor++'
#          patch-wording: 'patch++'
#          target-branch: 'main'
#          tag-prefix: 'v'
#          skip-push:  'true'
#          skip-commit: 'true'
#          skip-tag: 'true'


#      - name: Update Tags
#        uses: vweevers/additional-tags-action@v1

#      - name: Build release changelog
#        id: github_release
#        uses: mikepenz/release-changelog-builder-action@main
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          configuration: "configs/configuration.json"
#
#      - name: Create Release
#        uses: ncipollo/release-action@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag: ${{ steps.bump.outputs.newTag }}
#          name: ${{ steps.bump.outputs.newTag }}
#          body: ${{steps.github_release.outputs.changelog}}
#          owner: Ann2827
#          repo: library-react-hooks
#          token: ${{ secrets.GITHUB_TOKEN }}
#          artifacts: "build/*.zip"
#          bodyFile: "build/*.zip"
#          draft: true
#          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}

#  generate_changelog:
#    runs-on: ubuntu-latest
#    needs: [release]
#    name: Generate changelog for master branch
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Generate changelog
#        uses: charmixer/auto-changelog-action@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
##
#      - name: Commit files
#        run: |
#          git config --local user.email "ann.bystrova96@mail.ru"
#          git config --local user.name "Ann Bystrova"
#          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to CHANGELOG.md"
#
#      - name: Push changes
##        if: env.push == 'true'
#        env:
#          CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          git push "https://Ann2827:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:main
